server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #paymen_routh   #路由的Id，没有固定归职责但是要求唯一，建议配合服务名
        # uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service    #匹配后提供服务的路由地址
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/get/**          #断言，路径匹配的进行路由

        - id: payment_routh2 #paymen_routh  #路由的Id，没有固定归职责但是要求唯一，建议配合服务名
         #uri: http://localhost:8001      #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service    #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**           #断言，路径匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service #eureka服务的的实例名称
  client:
    service-url:
      register-with-eureka: true
        #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
      fetch-registry: true
      #设置与Eureka Server交互的地址查询服务和注册服务都需要以来这个地址。
      #defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
    #false表示不向注册中心注册自己


