server:
  port: 80
eureka:
  client:
    #false表示不向注册中心注册自己,表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要以来这个地址。
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
logging:
  level:
    com.zhu.springcloud.service.PaymentFeignService: debug
