server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
  client:
    #false表示不向注册中心注册自己,表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单点无所谓，集群必须设置为true才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
    #设置与Eureka Server交互的地址查询服务和注册服务都需要以来这个地址。
      defaultZone: http://eureka7001.com:7001/eureka